name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - name: Fetch tags
        run: git fetch --depth=100 origin +refs/tags/*:refs/tags/*
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
      - name: Checking your code format
        run: csbt scalafmtCheck
      - name: Cache dependencies
        uses: actions/cache@v2.1.4
        with:
          path: ~/.cache/coursier/v1
          key: ${{ runner.os }}-coursier-${{ hashFiles('build.sbt') }}-${{ hashFiles('project/*.scala') }}
          restore-keys: ${{ runner.os }}-coursier-
      - name: Cache .sbt
        uses: actions/cache@v2.1.4
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('build.sbt') }}-${{ hashFiles('project/*.scala') }}
          restore-keys: ${{ runner.os }}-sbt-
      - name: Run tests
        run: |
          csbt +test
          SCALAJS_VERSION=0.6.33 csbt clean +test
